package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String country;
   private java.lang.String zipcode;
   private java.lang.String cityName;
   private java.lang.String streetNumber;
   private java.lang.String streetName;

   public Address()
   {
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public java.lang.String getZipcode()
   {
      return this.zipcode;
   }

   public void setZipcode(java.lang.String zipcode)
   {
      this.zipcode = zipcode;
   }

   public java.lang.String getCityName()
   {
      return this.cityName;
   }

   public void setCityName(java.lang.String cityName)
   {
      this.cityName = cityName;
   }

   public java.lang.String getStreetNumber()
   {
      return this.streetNumber;
   }

   public void setStreetNumber(java.lang.String streetNumber)
   {
      this.streetNumber = streetNumber;
   }

   public java.lang.String getStreetName()
   {
      return this.streetName;
   }

   public void setStreetName(java.lang.String streetName)
   {
      this.streetName = streetName;
   }

   public Address(java.lang.String country, java.lang.String zipcode,
         java.lang.String cityName, java.lang.String streetNumber,
         java.lang.String streetName)
   {
      this.country = country;
      this.zipcode = zipcode;
      this.cityName = cityName;
      this.streetNumber = streetNumber;
      this.streetName = streetName;
   }

}