package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BaseElement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String caluculatedAttributeList;

   public BaseElement()
   {
   }

   public java.lang.String getCaluculatedAttributeList()
   {
      return this.caluculatedAttributeList;
   }

   public void setCaluculatedAttributeList(
         java.lang.String caluculatedAttributeList)
   {
      this.caluculatedAttributeList = caluculatedAttributeList;
   }

   public BaseElement(java.lang.String caluculatedAttributeList)
   {
      this.caluculatedAttributeList = caluculatedAttributeList;
   }

}