package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Period implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.Date desidedStartDate;
   private java.lang.String seasonType;

   public Period()
   {
   }

   public java.util.Date getDesidedStartDate()
   {
      return this.desidedStartDate;
   }

   public void setDesidedStartDate(java.util.Date desidedStartDate)
   {
      this.desidedStartDate = desidedStartDate;
   }

   public java.lang.String getSeasonType()
   {
      return this.seasonType;
   }

   public void setSeasonType(java.lang.String seasonType)
   {
      this.seasonType = seasonType;
   }

   public Period(java.util.Date desidedStartDate, java.lang.String seasonType)
   {
      this.desidedStartDate = desidedStartDate;
      this.seasonType = seasonType;
   }

}