package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String gender;
   private java.lang.Integer age;
   private java.math.BigDecimal standardPrice;
   private java.util.Date birtthDate;
   private java.lang.String surname;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.math.BigDecimal getStandardPrice()
   {
      return this.standardPrice;
   }

   public void setStandardPrice(java.math.BigDecimal standardPrice)
   {
      this.standardPrice = standardPrice;
   }

   public java.util.Date getBirtthDate()
   {
      return this.birtthDate;
   }

   public void setBirtthDate(java.util.Date birtthDate)
   {
      this.birtthDate = birtthDate;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public Person(java.lang.String name, java.lang.String gender,
         java.lang.Integer age, java.math.BigDecimal standardPrice,
         java.util.Date birtthDate, java.lang.String surname)
   {
      this.name = name;
      this.gender = gender;
      this.age = age;
      this.standardPrice = standardPrice;
      this.birtthDate = birtthDate;
      this.surname = surname;
   }

}