package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String period;
   private java.util.Date validUntil;
   private java.lang.Boolean subscription;
   private java.util.Date quoteDate;
   private java.lang.String priceList;
   private java.lang.String address;
   private java.lang.String personList;

   public Quote()
   {
   }

   public java.lang.String getPeriod()
   {
      return this.period;
   }

   public void setPeriod(java.lang.String period)
   {
      this.period = period;
   }

   public java.util.Date getValidUntil()
   {
      return this.validUntil;
   }

   public void setValidUntil(java.util.Date validUntil)
   {
      this.validUntil = validUntil;
   }

   public java.lang.Boolean getSubscription()
   {
      return this.subscription;
   }

   public void setSubscription(java.lang.Boolean subscription)
   {
      this.subscription = subscription;
   }

   public java.util.Date getQuoteDate()
   {
      return this.quoteDate;
   }

   public void setQuoteDate(java.util.Date quoteDate)
   {
      this.quoteDate = quoteDate;
   }

   public java.lang.String getPriceList()
   {
      return this.priceList;
   }

   public void setPriceList(java.lang.String priceList)
   {
      this.priceList = priceList;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getPersonList()
   {
      return this.personList;
   }

   public void setPersonList(java.lang.String personList)
   {
      this.personList = personList;
   }

   public Quote(java.lang.String period, java.util.Date validUntil,
         java.lang.Boolean subscription, java.util.Date quoteDate,
         java.lang.String priceList, java.lang.String address,
         java.lang.String personList)
   {
      this.period = period;
      this.validUntil = validUntil;
      this.subscription = subscription;
      this.quoteDate = quoteDate;
      this.priceList = priceList;
      this.address = address;
      this.personList = personList;
   }

}