package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class subscription implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String type;
   private java.util.Date validUntil;
   private java.util.Date validFrom;
   private java.math.BigDecimal price;

   public subscription()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.util.Date getValidUntil()
   {
      return this.validUntil;
   }

   public void setValidUntil(java.util.Date validUntil)
   {
      this.validUntil = validUntil;
   }

   public java.util.Date getValidFrom()
   {
      return this.validFrom;
   }

   public void setValidFrom(java.util.Date validFrom)
   {
      this.validFrom = validFrom;
   }

   public java.math.BigDecimal getPrice()
   {
      return this.price;
   }

   public void setPrice(java.math.BigDecimal price)
   {
      this.price = price;
   }

   public subscription(java.lang.String type, java.util.Date validUntil,
         java.util.Date validFrom, java.math.BigDecimal price)
   {
      this.type = type;
      this.validUntil = validUntil;
      this.validFrom = validFrom;
      this.price = price;
   }

}